### ISSUE TITLE
Generating snapshot script fails with "Cannot replace with lazy function because the supplied node does not belong to an assignment"

### ISSUE THREAD

**Issue by juturu** [atom/electron-link#2]
Following is the error - any help in debugging this further?

`Generating snapshot script at "\build\startup.js" (9)MemberExpression
MemberExpression
CallExpression
ExpressionStatement
Program
[17:27:48] 'makesnapshot' errored after 467 ms
[17:27:48] Error: \build\lib\main.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
    at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (\node_modules\electron-link\lib\file-require-transform.js:181:11)
    at Context.recast.types.visit.visitIdentifier (\node_modules\electron-link\lib\file-require-transform.js:72:18)
    at Context.invokeVisitorMethod (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:344:49)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:196:32)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at NodePath.each (\node_modules\recast\node_modules\ast-types\lib\path.js:101:26)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at visitChildren (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:204:20)
    at Visitor.PVp.visit (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:133:29)
    at Object.visit (\node_modules\recast\node_modules\ast-types\lib\path-visitor.js:101:55)
    at FileRequireTransform.replaceDeferredRequiresWithLazyFunctions (\node_modules\electron-link\lib\file-require-transform.js:68:20)`

**Comment by cruzlauroiii** [comment]
need to support latest node version i think

**Comment by LennardF1989** [comment]
Did you ever figure this one out?

**Comment by astoilkov** [comment]
I am getting the error shown below. Anyone know what the reason for this error is?

```
Error: /Users/astoilkov/Caret/node_modules/electron/index.js
Cannot replace with lazy function because the supplied node does not belong to an assignment expression or a variable declaration!
    at FileRequireTransform.replaceAssignmentOrDeclarationWithLazyFunction (/Users/astoilkov/Caret/node_modules/electron-link/lib/file-require-transform.js:180:11)
    at Context.visitIdentifier (/Users/astoilkov/Caret/node_modules/electron-link/lib/file-require-transform.js:72:18)
    at Context.invokeVisitorMethod (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:344:49)
    at Visitor.PVp.visitWithoutReset (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:196:32)
    at visitChildren (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/Users/astoilkov/Caret/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:204:20)
```

**Comment by yonas** [comment]
I'm also getting this error. Using node 8.8.1

**Comment by aminya** [comment]
Same error here at https://github.com/atom/atom/pull/20965.

**Comment by aminya** [comment]
I made a pull request that fixes this! This should be soon available in the next version. #27
